### ISSUE TITLE
La sessione una volta il logout in qualche modo non viene pulita

### ISSUE THREAD

**Issue by caamillo** [47PADO47/Classeviva.js#12]
Attualmente appena faccio .logout() e magari nel prossimo login sbaglio un campo (come ad esempio inserire come email `a@a.it`) mi fa riloggare con la precedente sessione
[https://i.imgur.com/2hEhs4T.png](url)

**Comment by 47PADO47** [comment]
Si è normale, in quanto prima di fare login controlla se esiste un file con L ultimo token salvato e se questo non è scaduto evita di chiamare il server per crearne uno nuovo

**Comment by 47PADO47** [comment]
Comunque avevi già pianificato degli aggiornamenti da pushare, appena riesco aggiungi L opzione per disattivare la parte del file temp

**Comment by caamillo** [comment]
Ok perfetto, grazie mille

**Comment by caamillo** [comment]
appena pushi puoi menzionare questo issue?

**Comment by 47PADO47** [comment]
@caamillo Ho aggiornato il pacchetto alla versione [3.1.0](../releases/tag/v3.1.0), trovi il nuovo esempio nella cartella docs

**Comment by caamillo** [comment]
[](blob:https://imgur.com/a2bb78a2-fbf0-4d6a-aade-0b5f409925b4)
Sembra esserci questo errore ora comunque

**Comment by caamillo** [comment]
[blob:https://imgur.com/a2bb78a2-fbf0-4d6a-aade-0b5f409925b4](url)

**Comment by caamillo** [comment]
[https://i.imgur.com/G6Tviie.png](url)

**Comment by caamillo** [comment]
Viene throwato quando sbaglio pw

**Comment by 47PADO47** [comment]
Non capisco quale sia il problema. Ti da L errore quando sbagli password con quando le credenziali sono corrette?

**Comment by 47PADO47** [comment]
Perché se sbagli password per forza ti darà un errore 😂. Come scritto nella release, adesso quando c'è qualcosa di sbagliato utilizza Promise.reject, che risulterà in un errore come stampato nell immagine. Per evitare che il codice esploda ti consiglio di utilizzare il metodo Promise.catch o mettere il tutto in un blocco try-catch.

**Comment by caamillo** [comment]
Il problema è che prima non faceva process.exit nel caso di un login sbagliato. L'errore non viene handlato prima della promise

**Comment by caamillo** [comment]
So che posso benissimo bypassare questo problema con un try catch.

**Comment by caamillo** [comment]
Anzi se sapessi TS ti avrei da subito aiutato, anche per qualche altra piccola funzionalità

**Comment by caamillo** [comment]
Comunque grazie lo stesso, mi hai aiutato parecchio con la repo 😊
