### ISSUE TITLE
Rest Class not existing

### ISSUE THREAD

**Issue by caamillo** [47PADO47/Classeviva.js#9]
[](https://i.imgur.com/lVQPLY2.png)

**Comment by caamillo** [comment]
https://imgur.com/a/t3dOexm

**Comment by 47PADO47** [comment]
Dovrei avere fixato nella versione 3.0.2, anche se potrebbe chiederti installazione di tslib

**Comment by 47PADO47** [comment]
Poi fammi sapere se funziona che chiudo issue

**Comment by caamillo** [comment]
installando anche tslib funziona, gracias
